#!/usr/bin/env bash
# Function to display subdomain information

display_info() {
    local domain="$1"
    local subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig "$sub.$domain" | awk '/^'${sub}'\.'${domain}'\./ { print $1,$4,$5 }')
        echo "The subdomain $sub is $result"
    done
}

# Main script
# if [[ $# -eq 0 ]]; then
# echo "Usage: $0 <domain> [<subdomain>]"
# exit 1
# fi

# domain="$1"
# subdomain="$2"

# display_info "$domain" "$subdomain"
