#!/usr/bin/env bash
# Function to display subdomain information

domain=$1
subdomain=$2

# Function to print domain information
print_domain_info() {
    local record_type=$(echo "$result" | awk '{print $4}')
    local ip_addr=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $ip_addr"
}

# Function to get domain information
get_domain_info() {
    if [[ -z $domain ]]; then
        echo "Domain name missing."
        exit 1
    fi

    if [[ -z $subdomain ]]; then
        known_sub_domains=("www" "lb-01" "web-01" "web-02")
        for sub in "${known_sub_domains[@]}"; do
            result=$(dig "$sub.$domain" | awk '/^'${sub}'\.'${domain}'\./ { print $0 }' | tail -1)
            print_domain_info
        done
    else
        result=$(dig "$subdomain.$domain" | awk '/^'${subdomain}'\.'${domain}'\./ { print $0 }' | tail -1)
        print_domain_info
    fi
}

get_domain_info
