#!/usr/bin/env bash
# Function to display subdomain information

domain_info () {
    local result
    result=$(dig "$2"."$1" | awk "/^'${2}'\.'${1}'\./ { print $1,$4,$5 }")
    echo "The subdomain $2 is $result"
}

if [ "$#" -eq 1 ]; then
  domain_info "$1" "www"
  domain_info "$1" "lb-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_info "$1" "$2"
else
  echo "Usage: $0 <domain> [<subdomain>]"
  exit 1
fi
