#!/usr/bin/env bash
# This script transfers a file from a client to a server

[ "$#" -lt 4 ] && { echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"; exit 1; }

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/ && echo "File transfer successful"
