#!/usr/bin/env bash
# This script installs nginx and configures it on a remote server.

apt-get -y update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
