#!/usr/bin/env bash
# Install nginx

apt-get update
apt-get install -y nginx

# Configure nginx to redirect /redirect_me with a 301 Moved Permanently
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
