#!/usr/bin/env bash
# Update package index and install nginx

sudo apt update
sudo apt install -y nginx

# Define the custom header value
HOSTNAME=$(hostname)

# Configure Nginx to add custom header
sudo bash -c 'cat <<EOF > /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Served-By $HOSTNAME;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
