#!/bin/bash

# Update package index and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 517706-web-01:80 check
    server web-02 517706-web-02:80 check
EOF'

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
