#!/usr/bin/env bash
# Update package index and install HAProxy

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load_balancer
    bind :80
    bind :8080
    mode http
    balance roundrobin
    option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
    option forwardfor
    server 517706-web-01 54.152.235.22 check port 80
    server 517706-web-02 35.175.64.89 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
