#!/usr/bin/env bash
# Function to check if Nginx is listening on port 80

rm /etc/nginx/sites-enabled/default
# correct the symbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# start service
sudo service nginx restart
