#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
#+ with a sleep of 2 seconds between each iteration.
# It responds to SIGTERM by printing "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
