#!/usr/bin/env bash
# This script tells the story of /etc/passwd users

# Read /etc/passwd line by line using while loop and IFS
while IFS=':' read -r username passcode userid groupid info home shell; do

  # Display user information
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $info"
done < "/etc/passwd"
