#!/usr/bin/env bash
# Script to display active IPv4 IPs

# Use ifconfig to get active IPv4 IPs and filter the output
ifconfig | grep -oP 'inet (addr:)?\K([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v '127.0.0.1'
